document.addEventListener('DOMContentLoaded',function(){
const data=[
{t:'Desde que entré en la menopausia todo se complicó. Probé varias cosas por mi cuenta pero no veía resultados. Antonio me explicó bien qué le pasaba a mi cuerpo con los cambios hormonales y me dio pautas realistas. He perdido peso poco a poco en estos meses, pero lo mejor es que tengo más energía durante el día y duermo mejor.',n:'María José, 56 años',c:'Murcia'},
{t:'Pensaba que a mi edad ya era imposible cambiar nada. Antonio me hizo ver que no era así. Me preparó menús sencillos y me enseñó a combinar bien los alimentos. He perdido peso pero sin quedarme débil, que era mi miedo. Me noto más ágil y la digestión me funciona mucho mejor.',n:'Teresa, 61 años',c:'Cartagena'},
{t:'La verdad es que fui un poco escéptica al principio. Pero Antonio fue muy claro desde el inicio: nada de milagros, solo constancia. Me ayudó a ordenar mis comidas y a entender por qué antes no me funcionaba. No fue tan rápido como esperaba, en 6 meses he bajado 7 kilos, pero lo importante es que llevo varios meses manteniéndolos sin esfuerzo.',n:'Ana, 52 años',c:'Alicante'},
{t:'Lo que más me agobiaba era la hinchazón y los cambios de ánimo. Antonio no solo me dio una dieta, sino que me explicó cómo ciertos alimentos me afectaban más que otros. He notado cambios en el peso, pero sobre todo me siento menos pesada y con mejor humor. Y responde siempre que le escribo, eso se agradece.',n:'Carmen, 58 años',c:'Madrid'},
{t:'Tengo problemas de rodilla y no puedo hacer mucho ejercicio. Antonio lo tuvo en cuenta desde el principio y adaptó todo a lo que yo sí podía hacer: caminar y comer mejor. Llevo 2 meses y ya he bajado 3 kilos, voy despacio pero voy bien. Me he quitado algunos centímetros de cintura y lo mejor es que no paso hambre. Aún me queda, pero voy con confianza.',n:'Pilar, 63 años',c:'Valencia'},
{t:'Después de tantos intentos fallidos, ya no quería oír hablar de dietas. Antonio me convenció porque no me habló de prohibiciones, sino de cambiar hábitos poco a poco. He perdido peso de forma gradual y llevo bastantes meses manteniendo el resultado sin agobios. Eso para mí ya es un éxito.',n:'Rosa, 54 años',c:'Murcia'},
{t:'Corro medias maratones y quería perder algo de grasa sin perder rendimiento. Me costó un poco ajustar los carbohidratos los días de descanso, pero Antonio me fue guiando. He perdido grasa corporal y he mejorado mi marca en 4 minutos. No esperaba ese cambio tan notable.',n:'Elena, 49 años',c:'Lorca'},
{t:'Con 53 años ya no esperaba grandes cambios. Las primeras semanas me costó dejar la cerveza entre semana, no voy a mentir. Pero en unos meses he bajado bastante peso y me noto mucho mejor físicamente. Mi médico me ha bajado la medicación de la tensión, que era uno de mis objetivos. Ahora entreno con más ganas.',n:'José Manuel, 53 años',c:'Murcia'},
{t:'Hago ciclismo los fines de semana y quería rendir más en las subidas. Antonio me ajustó la alimentación según mis entrenamientos y la diferencia se nota. He bajado algo de peso y subo los puertos con más fuerza y sin esa sensación de vacío a mitad de ruta. Estoy muy contento.',n:'Antonio, 46 años',c:'Almería'},
{t:'Entrenaba regularmente pero seguía con barriga. Antonio me explicó que el problema no era solo el ejercicio, sino cómo y cuándo comía. He perdido 8 centímetros de cintura en 4 meses sin dejar de disfrutar de la comida. Era justo lo que necesitaba.',n:'Juan Carlos, 51 años',c:'Murcia'}
];
const box=document.getElementById('carousel');
if(!box)return;
box.innerHTML=data.map(function(d,i){return '<div class="slide'+(i===0?' active':'')+'"><p class="text-muted">'+d.t+'</p><p class="mt-6 font-bold">'+d.n+'</p><p class="text-sm text-muted">'+d.c+'</p></div>';}).join('');
});
